### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m2-evaluacion-intermedia-AnaAmaro#1]
Really cool job @AnaAmaro !!!

Here you have some tips to improve the exercise:

### Structure

- [x] Define a good structure of folders and files for the project

### HTML

- [x] Add HTML elements for the game: title, label and input, button, space for feedback (`div`, `p`) and number of trials
- [x] Use a `label` to define the content of the input
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input
- [x] Use placeholder attribute instead of value one to show a field's hint
### Further challenges

Let me know if you have any doubts ;)

Go for it!!

**Comment by migueldelmazo** [comment]
La parte de JS está impecable, no puedo corregirte nada. Ana tienes que sentirte orgullosa de este ejercicio!!!

**Comment by AnaAmaro** [comment]
Thanks for the feedback. Corrected :)
